services:
  - type: web
    name: restaurant-reservation-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python reservation_app.py"
    envVars:
      - key: FLASK_ENV
        value: development
